### ISSUE TITLE
Connecting 7Pad to my DAW

### ISSUE THREAD

**Issue by Zeioth** [mixticninja/7PadMidi#1]
Hi! I'm following [the manual](http://163.172.94.38/wp-content/uploads/2016/09/7PadConnexion-DAW-EN.pdf) to connect 7Pad to my DAW on linux.

I'm running 7PadMidi correctly, and now I'm creating a 'virtual midi cable'. I was able to do it  by [running](https://ubuntuforums.org/showthread.php?t=1445186)

    sudo modprobe snd-virmidi

I can see the new midi connection in LMMS (my DAW), but not in 7Pad. Any ideas? Thank you.

**Comment by Zeioth** [comment]
Screens of what I've achieved so far:
![7p4](https://user-images.githubusercontent.com/3357792/29753155-70739cae-8b6b-11e7-8385-10f7d7396748.png)
It connects but inmediatelly disconnects.
![7p2](https://user-images.githubusercontent.com/3357792/29753120-d3eb011a-8b6a-11e7-8fa4-a35a7cad5c63.png)
![7p3](https://user-images.githubusercontent.com/3357792/29753137-132858dc-8b6b-11e7-973d-5a3385ea1599.png)
![7p5](https://user-images.githubusercontent.com/3357792/29753658-8c2587cc-8b76-11e7-89c5-73bca837eb7d.png)

**Comment by mixticninja** [comment]
I answered in Twitter,  "using jackmidi on Linux : wire it to your vir cable and select it in 7pad." try and tell me... I can help more when back to the
studio next week. Thx for you interest.

**Comment by Zeioth** [comment]
I'm reading the code... My best guess is that when ServerSocketThread.run() executes the method reader.readCommand(), something bad happens and raises an exception that executes ServerSocketThread.closeAll()

That's why it connects but then disconnects instantly. I'm no expert in java, but I'll try to debug and compile it.

ServerSocketThread.java
![e1](https://user-images.githubusercontent.com/3357792/29795014-b1c6b170-8c4a-11e7-88ee-5ec499cdeaf4.png)

FingerReader.java
![e2](https://user-images.githubusercontent.com/3357792/29795015-b1cc4946-8c4a-11e7-8799-9a0f0b5d271f.png)

**Comment by mixticninja** [comment]
You can fork it an try...  This server code is tested working on Linux and
Windows machines...  If it doesn't work for you, my guess it may comes from
your network setup. I'll be curious off your investigations and possible
optimization on this side.
For the jack part it's working here on my holiday pc and I could play my
Bitwig daw  on Linux laptop with my android 7pad phone connected on a bar
wifi at he beach.  😎
Thx for your interest.  More for Linux users in September.

**Comment by Zeioth** [comment]
I've been researching a bit. It looks that 7Pad(android) connects with 7PadMIDI, but the smartphone is sending an empty stream.

![test](https://user-images.githubusercontent.com/3357792/29896970-40bb02c4-8ddf-11e7-8634-e9b68fd90794.png)

My ports are open and my firewall disabled:

![firewall](https://user-images.githubusercontent.com/3357792/29897424-16f5db4c-8de1-11e7-8df9-42626710dafc.png)
![ports](https://user-images.githubusercontent.com/3357792/29898640-26780616-8de7-11e7-98de-030321be98f2.png)


Tomorrow i'll research a bit more.

**Comment by mixticninja** [comment]
As i suspected earlier, looks like the server you run  do the normal job here rejecting empty streams, the issue may come from what you (your jack midi virtual cable ) sends to it.
The Linux Jack and virtual midi cable + daw configuration is not part of 7PadMidi server but is part from a new tutorial for linux users check it out !
https://youtu.be/FfmejNrxce8

**Comment by Zeioth** [comment]
I'm not sure what is the exact input that 7PadMIDI is waiting for. I've managed to connect my android phone in MIDI mode, and now, qjackctl recognize it. I've tried every possible combination of connections in qjackctl, but still no luck. 7PadMidi always gets an empty stream.

![2017-08-31 21 02 00](https://user-images.githubusercontent.com/3357792/29940791-a35cc2d0-8e90-11e7-85fc-72c642da17bc.png)
![str](https://user-images.githubusercontent.com/3357792/29941089-9a6a0c86-8e91-11e7-8e17-0e48b08f8e8b.png)

**Comment by mixticninja** [comment]
Issue closed, not a 7PadMidi Problem

**Comment by Zeioth** [comment]
Thank you so much for the tutorial!! Sadly i haven't been able to reproduce the steps in none of my three computers.

**Server:**
I recorded [this short video](https://www.youtube.com/watch?v=8Mp44UUL06E&feature=youtu.be) following your steps one by one.

    Problem: "New client connection accepted" -> "Client dissconnected"

**Client:**
[Screenshot here](https://i.imgur.com/VTrPQtz.png).

    Problem: "No Midi device is selected, midi control will not work"

**More info:**

* [qjackctl status](https://i.imgur.com/H7x8ISs.png)
* [qjackctl config](https://i.imgur.com/TUN819F.png)
* [qjackctl misc](https://i.imgur.com/oOGM9K6.png)
* [testing ports client side](https://i.imgur.com/CDhnUGT.png)
* [testing ports server side(the connection remains open with using telnet)](https://i.imgur.com/UaD49VQ.png)

**Question:**
Were you able to reproduce those steps in a fresh installed computer?

**Comment by mixticninja** [comment]
Zeioth, for your personal comments and problems concerning 7Pad please use e-mail directly : mixticninja@gmail.com.  I'll be happy to try answering all your questions about our product. This issue thread is closed because your problem is not related to this 7PadMidi server only github page, so you should  stop using it. Thank you.
